### PR TITLE
Create Readme.md

### PR DESCRIPTION
**Pull request by katyamust**
readme initial version

### CODE REVIEW

**Review by MarekLani — APPROVED** [review]

**Comment by evgri243** [comment]
I was thinking about adding some highlights pointing to devcontainer, devexp, pipelines, but not yet sure how to approach that

**Comment by katyamust** [comment]
@evgri243 This is not finished I am working on it still. if you have suggestions or text please feel free to suggest to this. Let create it together. Idea is that any one who would like to use approach will get overview what the repo is and how to use.

**Comment by evgri243** [comment]
@MarekLani, @spoplavskiy, may I ask you to add a few lines on DevOps and Int testing at the end of the Getting Started section?

**Comment by katyamust** [comment]
Updated with updated from @evgri243 directly to branch. All looks good - merging

**Pull request merged**
